# Site settings
title: Hwansul
description: The black art for wandering programmer🕶
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://Hwansul.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# Space settings
space_name: Hwansul
space_description: Profile page for my personal command line interface programs. It has only a program for my personal tasks with google, microsoft and other well known major software platforms.
space_title: Space for commands
email: mindullestudio@gmail.com
# twitter_username: lorem_ipsum
# instagram_username: mauriciourraco7
# facebook_username: mauricio.urraco
# linkedin_username: murraco
github_username:  Hwansul
github_cli_repo:  Hwansul/cli-template
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum


exclude: ['package.json', 'src', 'node_modules', 'vendor']

